steps:
  # Fetch the credentials from the GCP bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://vibi-secrets-prod/pubsub-sa.json', 'pubsub-sa.json']
  
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://vibi-secrets-prod/repoprofiler_private.pem', 'repo-profiler.pem']


  # Perform cargo build inside vibi-dpu directory
  - name: 'rust:latest'
    entrypoint: 'cargo'
    args: ['build']
    dir: 'vibi-dpu'

  # Build the Docker image with the build arguments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'GCP_CREDENTIALS=$_GCP_CREDENTIALS'
      - '--build-arg'
      - 'SERVER_URL=$_SERVER_URL'
      - '--build-arg'
      - 'INSTALL_ID=$_INSTALL_ID'
      - '--build-arg'
      - 'BITBUCKET_CLIENT_ID=$_BITBUCKET_CLIENT_ID'
      - '--build-arg'
      - 'BITBUCKET_CLIENT_SECRET=$_BITBUCKET_CLIENT_SECRET'
      - '--build-arg'
      - 'BITBUCKET_BASE_URL=$_BITBUCKET_BASE_URL'
      - '--build-arg'
      - 'GITHUB_APP_ID=$_GITHUB_APP_ID'
      - '--build-arg'
      - 'GITHUB_APP_CLIENT_ID=$_GITHUB_APP_CLIENT_ID'
      - '--build-arg'
      - 'GITHUB_APP_CLIENT_SECRET=$_GITHUB_APP_CLIENT_SECRET'
      - '--build-arg'
      - 'GITHUB_BASE_URL=$_GITHUB_BASE_URL'
      - '-t'
      - 'asia.gcr.io/$PROJECT_ID/dpu/dpu:$SHORT_SHA'
      - '.'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/$PROJECT_ID/dpu/dpu:$SHORT_SHA']

#  # Delete the previous compute instance
#   - name: 'gcr.io/cloud-builders/gcloud'
#     args: ['compute', 'instances', 'delete', 'dpu-instance', '--zone=asia-south1-c', '--quiet']

  # Deploy the Docker image to a Docker-optimized VM
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'instances', 'create-with-container', 'dpu-instance', '--container-image=asia.gcr.io/$PROJECT_ID/dpu-test/dpu-test:$SHORT_SHA', '--zone=asia-south1-c', '--machine-type=e2-small']
