steps:
  # Pull the Docker image from Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'asia-south1-docker.pkg.dev/$PROJECT_ID/dpu-test/dpu-test:$SHORT_SHA']

# Authenticate with the Kubernetes cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'dpu-cluster', '--region', 'asia-south1', '--project', '$PROJECT_ID']

  # Create a new deployment in the Kubernetes cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'user-deployment-test.yaml']
    env:
    - '_INSTALL_ID=$_INSTALL_ID'
    - '_NAME=$SHORT_SHA$_USER_ID'