apiVersion: apps/v1
kind: Deployment
metadata:
  name: $_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpu
  template:
    metadata:
      labels:
        app: dpu
    spec:
      containers:
      - name: $_NAME
        image: asia.gcr.io/$PROJECT_ID/dpu-test/dpu-test:$SHORT_SHA
        ports:
        - containerPort: 80
        env:
        - name: INSTALL_ID
          value: $_INSTALL_ID
