apiVersion: apps/v1
kind: Deployment
metadata:
  name: $NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpu
  template:
    metadata:
      labels:
        app: dpu
    spec:
      containers:
      - name: $NAME
        image: asia-south1-docker.pkg.dev/$PROJECT_ID/dpu-test/dpu-test:$SHORT_SHA
        ports:
        - containerPort: 80
        env:
        - name: INSTALL_ID
          value: $INSTALL_ID
